# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'fire-reporting' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fire-reporting
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'FirebaseFirestore'
  pod 'Firebase/Functions'
  pod 'Firebase/MLVision'		
  pod 'Firebase/MLVisionLabelModel'
  pod 'Firebase/MLModelInterpreter'
  pod 'Mapbox-iOS-SDK'
  pod 'IQKeyboardManager'
end
